### ISSUE TITLE
TypeError: Cannot read property 'Date' of undefined

### ISSUE THREAD

**Issue by familiadalousa** [papnkukn/eml-format#13]
Hello,

I just download the last version, ran the example using a eml file and returns this error:

TypeError: Cannot read property 'Date' of undefined
    at _read (/servidor_html/eurosisnergia-norte.com/s/node_modules/eml-format/lib/eml-format.js:374:23)
    at Object.emlformat.read (/servidor_html/eurosisnergia-norte.com/s/node_modules/eml-format/lib/eml-format.js:522:5)

**Comment by papnkukn** [comment]
Hmm, the parser returns an empty object somehow. Can you provide an example of EML file?

**Comment by familiadalousa** [comment]
Sorry, i cannot. This was months ago. I do not know which emailwas anymore.

**Comment by jaydevelopsstuff** [comment]
The reason I had this problem was because I was using `fs.readFileSync`'s buffer output without converting it to a string. So I took that output from fs and invoked `.toString` and that fixed my problem. Hope this helps!
