### ISSUE TITLE
Unable to get html source of an email

### ISSUE THREAD

**Issue by vletoux** [papnkukn/eml-format#25]
While analysing spam email, I found this example whose html source code cannot be extracted.
It opens successfully in outlook on html mode

Here is the image:
![image](https://user-images.githubusercontent.com/10632326/106617384-dfc57600-656e-11eb-9c2e-2eb5156e8913.png)

And the source code copy pasted as a gist
https://gist.github.com/vletoux/036e5cc06f4718f4aa74947933a0a394

My nodejs knowledge is too poor to have a successful root cause analysis

**Comment by zhanghaifeng213** [comment]
![image](https://user-images.githubusercontent.com/26516275/111490129-b7d44f80-8775-11eb-8a5a-36dff97b678a.png)
Add this code to the source code to have a try

**Comment by MarcVillain** [comment]
The code you provided does resolve the issue for me, thank you.

**Comment by papnkukn** [comment]
Thank you very much for the contribution
