### ISSUE TITLE
Charset other then "utf-8" 

### ISSUE THREAD

**Issue by andrzejQ** [papnkukn/eml-format#6]
Perhaps implementation of old type charset like "iso-8859-..." as for Content-Transfer-Encoding: "8bit" "binary" "8bitmime" "binarymime" is not difficult - see attached "eml-format-conv.js" source. (I am not experienced enough to make branch of this project).
[eml-format-conv.zip](https://github.com/papnkukn/eml-format/files/2302150/eml-format-conv.zip)

**Comment by papnkukn** [comment]
@andrzejQ thanks for contributing and providing the solution!

The code has been merged with the public release and availabe with version 0.6.0.
